[package]
name = "connectrpc-axum"
version = "0.0.7"
edition = "2024"
description = "Axum-style Connect RPC server"
readme = "../README.md"
repository = "https://github.com/washanhanzi/connectrpc-axum"
license = "MIT"

[dependencies]
axum = { workspace = true, features = ["multipart"] }
axum-core = { workspace = true }
axum-extra = { workspace = true, optional = true }
base64 = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
http = { workspace = true }
http-body = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true }
pbjson = { workspace = true }
pbjson-types = { workspace = true }
pin-project-lite = { workspace = true }
prost = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_qs = { workspace = true }
tokio = { workspace = true, optional = true }
tokio-stream = { workspace = true, optional = true }
tokio-util = { workspace = true, features = ["io"] }
tonic = { workspace = true, optional = true }
tonic-prost = { workspace = true, optional = true }
tonic-web = { workspace = true, optional = true }
tower = { workspace = true, features = ["full"] }
tower-http = { workspace = true, features = ["cors"] }

[features]
tonic = ["dep:tokio", "dep:tokio-stream", "dep:tonic", "dep:tonic-prost"]
tonic-web = ["tonic", "dep:tonic-web"]
