[package]
name = "connectrpc-axum-build"
version = "0.0.6"
edition = "2024"
description = "Code generation for connectrpc-axum"
readme = "../README.md"
repository = "https://github.com/washanhanzi/connectrpc-axum"
license = "MIT"

[dependencies]
anyhow = { workspace = true }
convert_case = { workspace = true }
pbjson-build = { workspace = true }
proc-macro2 = { workspace = true }
prost = { workspace = true }
prost-build = { workspace = true }
prost-reflect = { workspace = true }
prost-types = { workspace = true }
protoc-fetcher = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
tonic-prost-build = { workspace = true, optional = true }

[features]
default = []
tonic = ["dep:tonic-prost-build"]
